name: Build Flutter Web

on:
  push:
    branches: [ master ]  # You can adjust this to trigger on specific branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: suborbital/flutter@v1
        with:
          flutter-version: '3.x'  # Update with your desired Flutter version (e.g., '3.3.8')

      - name: Install dependencies
        run: flutter pub get

      - name: Build web project (assuming web-demo is the entry point)
        working-directory: ./web-demo
        run: flutter build web

      - name: Archive build output (optional)
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: ./build/web  # Adjust path if your build output is located elsewhere

      - name: Deploy to GitHub Pages (optional)  # Add deployment steps here
        uses: actions/deploy-pages@v1  # Uncomment this line and configure deployment
        if: success()  # Only deploy on successful builds
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          local-dir: ./build/web  # Adjust path based on build output location
          # Configure other deployment options as needed
